[build]
publish = "public"
command = "npm install tailwindcss @tailwindcss/cli && tailwindcss -i themes/project-portfolio/src/css/main.css -o static/css/main.css --minify && zola build --base-url https://winterstein.netlify.app"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.19.2"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.
[context.deploy-preview]
command = "npm install tailwindcss @tailwindcss/cli && tailwindcss -i themes/project-portfolio/src/css/main.css -o static/css/main.css --minify && zola build --base-url $DEPLOY_PRIME_URL"
